[package]
name = "fft-correlation"
version = "0.0.5"
edition = "2021"

[lib]
name = "fft_correlation"
crate-type = ["rlib", "cdylib"]

[features]
default = []
python = ["dep:pyo3", "pyo3/extension-module", "dep:numpy"]

[dependencies]
realfft = "3.5"
pyo3 = { version = "0.28.0", optional = true, features = ["abi3-py39"] }
numpy = { version = "0.28.0", optional = true }
